# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-20 00:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Batch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lot_number', models.PositiveIntegerField(default=0)),
                ('start_date', models.DateTimeField(verbose_name='date started')),
            ],
        ),
        migrations.CreateModel(
            name='runPeriod',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField(verbose_name='start time')),
                ('time_taken', models.DurationField(default=0)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='timer.Batch')),
            ],
        ),
    ]
