# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-23 10:50
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timer', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='runperiod',
            name='batch',
        ),
        migrations.AddField(
            model_name='batch',
            name='start_time',
            field=models.DateTimeField(default=datetime.datetime(2016, 8, 23, 11, 50, 33, 763000), verbose_name='start time'),
        ),
        migrations.AddField(
            model_name='batch',
            name='time_taken',
            field=models.DurationField(default=0),
        ),
        migrations.DeleteModel(
            name='runPeriod',
        ),
    ]
