# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-23 14:12
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timer', '0008_auto_20160823_1221'),
    ]

    operations = [
        migrations.AddField(
            model_name='batch',
            name='duration',
            field=models.DurationField(default=datetime.timedelta(0), verbose_name='duration'),
        ),
        migrations.AlterField(
            model_name='batch',
            name='start_time',
            field=models.DateTimeField(default=datetime.datetime(2016, 8, 23, 15, 12, 48, 599000), verbose_name='start time'),
        ),
    ]
