# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-25 08:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timer', '0010_auto_20160823_1523'),
    ]

    operations = [
        migrations.AlterField(
            model_name='batch',
            name='start_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='date started'),
        ),
        migrations.AlterField(
            model_name='batch',
            name='start_time',
            field=models.DateTimeField(verbose_name='start time'),
        ),
    ]
