# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-25 08:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timer', '0011_auto_20160825_0935'),
    ]

    operations = [
        migrations.AlterField(
            model_name='batch',
            name='start_time',
            field=models.DateTimeField(auto_now_add=True, verbose_name='start time'),
        ),
    ]
