# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-30 10:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('timer', '0012_auto_20160825_0937'),
    ]

    operations = [
        migrations.CreateModel(
            name='Process',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25, verbose_name='name')),
                ('std_hours', models.PositiveIntegerField(default=0)),
                ('std_resource', models.PositiveIntegerField(default=1)),
                ('std_qty', models.PositiveIntegerField(default=1)),
            ],
        ),
        migrations.AddField(
            model_name='batch',
            name='process',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='timer.Process'),
        ),
    ]
