# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-30 15:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timer', '0013_auto_20160830_1145'),
    ]

    operations = [
        migrations.AlterField(
            model_name='process',
            name='std_hours',
            field=models.FloatField(default=0),
        ),
    ]
